### ISSUE TITLE
Game test issues detected in a project with plugins

### ISSUE THREAD

**Issue by Oscar92player** [Liquidize/mvbeta#3]
Those issues are plugin related, and are based on my experience with a personal project, so it can happen with any plugin in any project from other users. Also, this project has been updated with the 1.6.0 beta files.

-It seems that some YEP plugins are causing issues when I try to start my project, such as a black screen (only I can hear the BGM and SE from the title screen), and I think those issues are related somehow with the game resolution if you've changed it in the plugin manager.

-The game crashes if I use the Preload Manager (for some reason, it stops working and you can't preload data anymore). The error message says that some game resources are not in the corresponding folder, when they are.

-Other issue I've found, is with SRDude Game Upgrade plugin, when it is ON in the plugin manager: the game does not start. You can only see the window in black, no BGM and no SE. I cannot even open the Console with F8, so I think that user will have issues if they need to use this plugin or the ones related to the game window.

I can't tell more about thise issues, since I have a lot of plugins installed in the project, and I can't even start a new game or load a saved file because I keep getting errors (maybe related with compatibility with the new MV version).

**Comment by Liquidize** [comment]
@Oscar92player Thanks for reporting the issue, unfortunately this stuff is not an issue with MV itself but an issue with the plugins. This is likely due to the long awaited change in the NwJS version that has accompanied 1.6.0. 

- Liquidize
